version: '3'

services:
  backend_nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ../static/:/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on: 
      - backend_web

  backend_web:
    build:
      dockerfile: deploy/Dockerfile
      context: ../
    container_name: web
    env_file: ../emailService/.env
    volumes: 
      - ../static/:/app/static/
    ports:
      - 8000:8000
    command: >
      bash -c "
        ./manage.py collectstatic --noinput;
        gunicorn --workers=4 --bind 0.0.0.0:8000 emailService.wsgi:application;"
  
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /data:/data