version: '3'

services:
  backend_nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on: 
      - web_backend

  backend_web:
    build: .
    volumes: 
      - ../static/:/root/email-service/static
    ports:
      - 8000:8000