version: '3'

services:
  backend_nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ../static/:/static/
      - ./nginx/emailService.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on: 
      - backend_web

  backend_web:
    build:
      dockerfile: deploy/Dockerfile
      context: ../
    container_name: web
    env_file: ../emailService/.env
    volumes: 
      - ../static/:/app/static/
    ports:
      - 8000:8000
    command: >
      bash -c "
        ./manage.py collectstatic --noinput;
        python manage.py makemigrations;                                    │
        python manage.py migrate;
        gunicorn --workers=4 --bind 0.0.0.0:8000 emailService.wsgi:application;"
    depends_on:
      - postgres

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /data:/data

  celery:
    build:
      dockerfile: deploy/Dockerfile
      context: ../  
    container_name: celery
    command: "celery -A emailService worker -l info"
    depends_on: 
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: ../emailService/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB='emailService'
      - POSTGRES_USER='emailServiceUser'
      - POSTGRES_PASSWORD='password'

  prometheus:
    image: prom/prometheus:v2.14.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    
  grafana:
    image: grafana/grafana:6.5.2
    container_name: grafana
    ports:
      - 3060:3000


volumes:
  pgdata: