# Generated by Django 3.1.5 on 2021-01-11 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('html', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_type', models.CharField(choices=[('UN', 'user.name'), ('UU', 'user.university'), ('UFS', 'user.fellow_students')], default=None, max_length=4)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField()),
                ('field_value', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('values_of_fields', models.TextField()),
                ('html_context', models.TextField()),
                ('text_context', models.TextField()),
                ('recipients', models.ManyToManyField(to='emails.EmailRecipient')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
    ]
